CREATE TABLE ADMINS
    (ADMIN_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT ADMIN_ID PRIMARY KEY,
    ADMIN_USERNAME VARCHAR(255),
    ADMIN_PASSWORD VARCHAR(255)
    );
    
    INSERT INTO ADMINS(ADMIN_USERNAME,ADMIN_PASSWORD) values('admin','admin');
    